export enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  AGENT_SESSION_INVALID = 'AGENT_SESSION_INVALID',
  AGENT_SESSION_REVOKED = 'AGENT_SESSION_REVOKED',
  AGENT_SESSION_EXPIRED = 'AGENT_SESSION_EXPIRED',
  AGENT_SESSION_NOT_FOUND = 'AGENT_SESSION_NOT_FOUND',

  AGENT_PAYMENTS_DISABLED = 'AGENT_PAYMENTS_DISABLED',
  PER_TX_LIMIT_EXCEEDED = 'PER_TX_LIMIT_EXCEEDED',
  DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',

  PAYMENT_REQUIRED_MALFORMED = 'PAYMENT_REQUIRED_MALFORMED',
  UNSUPPORTED_NETWORK = 'UNSUPPORTED_NETWORK',
  UNSUPPORTED_ASSET = 'UNSUPPORTED_ASSET',

  BRIDGE_PAYMENT_NOT_FOUND = 'BRIDGE_PAYMENT_NOT_FOUND',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',

  BALANCE_NOT_FOUND = 'BALANCE_NOT_FOUND',
  AGENT_SETTINGS_NOT_FOUND = 'AGENT_SETTINGS_NOT_FOUND',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}