export enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  AGENT_SESSION_INVALID = 'AGENT_SESSION_INVALID',
  AGENT_SESSION_REVOKED = 'AGENT_SESSION_REVOKED',
  AGENT_SESSION_EXPIRED = 'AGENT_SESSION_EXPIRED',

  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}